name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Auth GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/903685462877/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "github-actions@project-40cabc90-4d22-4606-b51.iam.gserviceaccount.com"

    - name: Configure Docker
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build & Push
      run: |
        docker build -t app ./app
        docker tag app europe-west1-docker.pkg.dev/project-40cabc90-4d22-4606-b51/docker-repo/app:${{ github.sha }}
        docker push europe-west1-docker.pkg.dev/project-40cabc90-4d22-4606-b51/docker-repo/app:${{ github.sha }}
    
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: gke-autopilot
        location: europe-west1

    - name: Deploy
      run: |
        sed -i "s|IMAGE_PLACEHOLDER|europe-west1-docker.pkg.dev/project-40cabc90-4d22-4606-b51/docker-repo/app:${{ github.sha }}|" k8s/deployment.yaml
        kubectl apply -f k8s/